### ISSUE TITLE
Source of author's code

### ISSUE THREAD

**Issue by luisoala** [Jeff-HOU/UROP-Adversarial-Feature-Matching-for-Text-Generation#1]
Hello Jeff,

Thanks for sharing your material. I am currently reading the same paper and was searching for the source code when I stumbled across your repo. May I ask where you got the source code from? Is this from the original authors? I would like to verify this before looking at their code in more depth.

Thanks for your help and best!
Pete

**Comment by Jeff-HOU** [comment]
Hi Pete,

Usually there are 3 ways to find related materials for a paper:
1. [The authors' university homepage](http://people.duke.edu/~yz196/)
2. [The authors' Github homepage](https://zhegan27.github.io/Paper.html)
3. If it's from a conference, then [Conference accepted paper page](https://icml.cc/Conferences/2017/Schedule?showEvent=773). But seems not here this time.

Hope this is helpful!
Jeff

**Comment by luisoala** [comment]
Hey Jeff,

Thanks for your reply. I checked Zhe Gan's homepage before but overlooked the code. Now I found it. Thanks for the pointer!

Best,
Pete
